<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Restaurant Agreement</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body style="margin: 0; padding: 0; border:0; font-size:12px; font-family:arial; color:#000000">
        <table border="0" cellpadding="0" cellspacing="0" width="740" style="font-size:12px; font-family:Arial; line-height:16px; margin:0 auto; color:#000000;">   
            <tr>
                <td height="12"></td>
            </tr>
            <tr>
                <td>
                    <table border="0" cellpadding="0" cellspacing="0" width="740" style="" >
                        <tr>
                            <td width="20"></td>
                            <td width="700" style="vertical-align:bottom ;"><img src="<?php echo TEMPLATE_IMG_PATH . 'mabiz-logo.jpg'; ?>" style="border:0px;" alt="logo"></td>
                            <td width="20"></td>

                        </tr>
                    </table>
                </td>
            </tr> <!-- end of header -->
            <tr>
                <td>
                    <table border="0" cellpadding="0" cellspacing="0" width="740">
                        <tr>
                            <td width="20"></td>
                            <td width="700">
                                <table border="0" cellpadding="0" cellspacing="0" width="700">
                                    <tr>
                                        <td height="20"></td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <table border="0" cellpadding="0" cellspacing="0" width="700">
                                                <tr>
                                                    <td height="20" valign="middle" style="background:#ff8308; text-align:center;font-size:12px; font-family:Arial; line-height:16px; font-weight:bold;color:#000000">CONTACT INFO</td>
                                                </tr>
                                                <tr>
                                                    <td height="8"></td>
                                                </tr>
                                                <tr>
                                                    <td><table border="0" cellpadding="0" cellspacing="0" width="700">
                                                            <tr>
                                                                <td width="96" height="16" valign="bottom" align="right" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000">Restaurant</td>
                                                                <td width="20" height="16" valign="bottom"></td>
                                                                <td width="314" height="16" valign="bottom" style="border-bottom:1px solid #8b8b8b; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"><?php echo $this->restaurant_name; ?>  </td>
                                                                <td width="80" height="16" valign="bottom" align="right" style="font-size:11px;font-weight:bold;  font-family:Arial; line-height:16px; color:#000000">Cell Phone</td>
                                                                <td width="20" height="16" valign="bottom"></td>
                                                                <td width="170" height="16" valign="bottom" style="border-bottom:1px solid #8b8b8b; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"> <?php echo $this->cellphone; ?> </td>
                                                            </tr>
                                                            <tr>
                                                                <td width="96" height="16" valign="bottom" align="right" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000">Address</td>
                                                                <td width="20" height="16" valign="bottom"></td>
                                                                <td width="314" height="16" valign="bottom" style="border-bottom:1px solid #8b8b8b; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"><?php echo $this->address; ?>  </td>
                                                                <td width="80" height="16" valign="bottom" align="right" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000">Fax</td>
                                                                <td width="20" height="16" valign="bottom"></td>
                                                                <td width="170" height="16" valign="bottom" style="border-bottom:1px solid #8b8b8b; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"><?php echo $this->fax; ?> </td>
                                                            </tr>
                                                            <tr>
                                                                <td width="96" height="16" valign="bottom" align="right" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000">City, State, Zip</td>
                                                                <td width="20" height="16" valign="bottom"></td>
                                                                <td width="314" height="16" valign="bottom" style="border-bottom:1px solid #8b8b8b; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"> <?php echo $this->city_state; ?> </td>
                                                                <td width="80" height="16" valign="bottom" align="right" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000">Email</td>
                                                                <td width="20" height="16" valign="bottom"></td>
                                                                <td width="170" height="16" valign="bottom" style="border-bottom:1px solid #8b8b8b; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"> <?php echo $this->email; ?> </td>
                                                            </tr>
                                                            <tr>
                                                                <td width="96" height="16" valign="bottom" align="right" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000">Contact Title</td>
                                                                <td width="20" height="16" valign="bottom"></td>
                                                                <td width="314" height="16" valign="top" style="border-bottom:1px solid #8b8b8b; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000">
                                                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="font-size:12px; font-family:Arial; line-height:16px; margin:0 auto; color:#000000; word-break:break-all;">
                                                                        <tbody>
                                                                            <tr>
                                                                                <td width="32%" valign="middle" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"><?php echo $this->owner_title; ?></td>
                                                                                <td width="28%" valign="middle" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000">&nbsp;Contact Name:&nbsp;</td>
                                                                                <td width="40%" valign="middle" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"><?php echo $this->owner_name; ?></td>
                                                                            </tr>
                                                                        </tbody>
                                                                    </table>

                                                                </td>
                                                                <td width="80" height="16" valign="bottom" align="right" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000">Contact 1</td>
                                                                <td width="20" height="16" valign="bottom"></td>
                                                                <td width="170" height="16" valign="bottom" style="border-bottom:1px solid #8b8b8b; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"><?php echo $this->contact1; ?></td>
                                                            </tr>
                                                            <tr>
                                                                <td width="96" height="16" valign="bottom" align="right" style="font-size:11px; font-family:Arial; line-height:16px;color:#000000"><span style="font-size:11px;font-weight:bold;  font-family:Arial; line-height:16px; color:#000000">Phone Number</span></td>
                                                                <td width="20" height="16" valign="bottom"></td>
                                                                <td width="314" height="16" valign="bottom" style="border-bottom:1px solid #8b8b8b; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"><?php echo $this->phone; ?></td>
                                                                <td width="80" height="16" valign="bottom" align="right" style="font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000">Contact 2</td>
                                                                <td width="20" height="16" valign="bottom"></td>
                                                                <td width="170" height="16" valign="bottom" style="border-bottom:1px solid #8b8b8b; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"><?php echo $this->contact2; ?></td>
                                                            </tr>
                                                        </table></td>
                                                </tr>
                                            </table>	
                                        </td>
                                    </tr>
                                </table>	
                            </td>
                            <td width="20"></td>
                        </tr>

                    </table>		

                </td>
            </tr> <!-- end of first part -->
        </table> <!-- end of first table -->
        <!-- second table start -->
        <!-- third table start -->
        <table border="0" cellpadding="0" cellspacing="0" width="740" style="font-size:11px; font-family:Arial; line-height:16px; margin:0 auto; color:#000000;"> 
            <tr>
                <td width="20"></td>
                <td width="700">
                    <table border="0" cellpadding="0" cellspacing="0" width="700" style="font-size:12px; font-family:Arial; line-height:16px; margin:0 auto; color:#000000;"> 
                        <tr>
                            <td height="8">&nbsp;</td>
                        </tr>
                        <tr>
                            <td>
                                <table width="700" border="0" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td width="700">
                                            <table width="700" border="0" cellpadding="0" cellspacing="0">
                                                <tr>
                                                    <td valign="middle" height="20" style="background:#ff8308; text-align:center;font-size:12px; font-family:Arial; line-height:16px; font-weight:bold;color:#000000">ADDITIONAL INFO</td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <table width="700" border="0" cellpadding="0" cellspacing="0">
                                                            <tr>
                                                                <td width="30%" align="right" style="padding:3px 10px; border-top:1px solid #000000;border-left:1px solid #000000;font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000; border-right:1px solid #000000" >Instructions</td>
                                                                <td width="70%" style="padding:3px 10px; border-right:1px solid #000000; border-top:1px solid #000000;font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000"><?php echo $this->rest_instructions; ?></td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <table width="700" border="0" cellpadding="0" cellspacing="0">
                                                            <tr>
                                                                <td width="30%" align="right" style="padding:3px 10px;  border-bottom:1px solid #000000; border-top:1px solid #000000;border-left:1px solid #000000;font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000; border-right:1px solid #000000" >Website</td>
                                                                <td width="70%" style="padding:3px 10px;  border-bottom:1px solid #000000;border-right:1px solid #000000; border-top:1px solid #000000;font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000"><?php echo $this->website; ?></td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <table width="700" border="0" cellpadding="0" cellspacing="0">
                                                            <tr>
                                                                <td width="30%" align="right" style="padding:3px 10px;  border-bottom:1px solid #000000; border-left:1px solid #000000;font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000;border-right:1px solid #000000">Sales Associate's Name</td>
                                                                <td width="70%" style="padding:3px 10px;  border-bottom:1px solid #000000;border-right:1px solid #000000; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000"><?php echo $this->associatename; ?></td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>

                                                <tr>
                                                    <td>
                                                        <table width="700" border="0" cellpadding="0" cellspacing="0">
                                                            <tr>
                                                                <td width="30%" align="right" style="padding:3px 10px;  border-bottom:1px solid #000000; border-left:1px solid #000000;font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000;border-right:1px solid #000000">Sales Associate's Email</td>
                                                                <td width="70%" style="padding:3px 10px;  border-bottom:1px solid #000000;border-right:1px solid #000000; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000"><?php echo $this->associateemail; ?></td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <table width="700" border="0" cellpadding="0" cellspacing="0">
                                                            <tr>
                                                                <td align="right" style="padding:3px 10px;  border-bottom:1px solid #000000; border-left:1px solid #000000;font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000;border-right:1px solid #000000">Sales Associate's Region</td>
                                                                <td style="padding:3px 10px;  border-bottom:1px solid #000000;border-right:1px solid #000000; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000"><?php echo $this->associateregion; ?></td>
                                                            </tr>
                                                            <tr>
                                                                <td width="30%" align="right" style="padding:3px 10px;  border-bottom:1px solid #000000; border-left:1px solid #000000;font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000;border-right:1px solid #000000">Phone1</td>
                                                                <td width="70%" style="padding:3px 10px;  border-bottom:1px solid #000000;border-right:1px solid #000000; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000"><?php echo $this->phone1; ?></td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <table width="700" border="0" cellpadding="0" cellspacing="0">
                                                            <tr>
                                                                <td width="30%" align="right" style="padding:3px 10px;  border-bottom:1px solid #000000; border-left:1px solid #000000;font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000;border-right:1px solid #000000">Phone2</td>
                                                                <td width="70%" style="padding:3px 10px;  border-bottom:1px solid #000000;border-right:1px solid #000000; font-size:11px; font-weight:bold; font-family:Arial; line-height:16px;color:#000000"><?php echo $this->phone2; ?></td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>



                                                <tr>
                                                    <td height="50" ></td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <table width="700" cellpadding="0" cellspacing="0" border="0">
                                                            <tr>

                                                                <td width="240" valign="bottom" height="16" style="padding:0px 0; font-weight:bold; font-size:12px; font-family:Arial; line-height:15px;  color:#000000;">Free Profile on Munch Ado signed up on</td>
                                                                <td width="190" valign="bottom" height="16" style="padding:0px 0;border-bottom:1px solid #8b8b8b; font-weight:bold; font-size:12px; font-weight:bold; font-family:Arial; line-height:16px; color:#000000"><?php echo $this->created_on; ?></td>
                                                                <td width="270"></td>
                                                            </tr>
                                                        </table>
                                                    </td>	
                                                </tr>

                                            </table>

                                        </td>
                                    </tr>

                                </table>

                            </td>
                        </tr>
                        <tr><td height="100"></td></tr>
                    </table>	

                </td>
                <td width="20"></td>

            </tr>
            <tr>
                <td colspan="3" height="300"><!--500-->
                </td>
            </tr>
            <tr>
                <td colspan="3">

                    <table border="0" cellpadding="0" cellspacing="0">
                        <tr>	
                            <td width="700"  align="center" style="vertical-align:bottom;font-size:9px; font-family:Arial; line-height:15px; color:#000000">
                                <p style="vertical-align:middle; margin:0;font-size:9px;  font-family:Arial; line-height:15px; color:#000000"><a href="https://munchado.com/" target="blank" style="text-decoration:none; color:#f5832d">www.munchado.com</a>&nbsp;&nbsp; 1-888-345-1303 &nbsp; 245 Fifth Avenue, Suite 1002, New York, NY 10016</p>
                                <p style="vertical-align:middle; margin:0;font-size:9px;  font-family:Arial; line-height:15px; color:#000000"><a href="https://www.facebook.com/MunchAdo" target="blank" style="text-decoration:none; color:#000000"><img src="<?php echo TEMPLATE_IMG_PATH . 'mabiz-facebook-icon.jpg'; ?>" style="vertical-align:middle" alt="facebook"> &nbsp;facebook.com/MunchAdo</a> &nbsp;&nbsp;&nbsp; <a href="https://twitter.com/@Munch_Ado" target="blank" style="text-decoration:none; color:#000000"><img src="<?php echo TEMPLATE_IMG_PATH . 'mabiz-twitter-icon.jpg'; ?>" style="vertical-align:middle" alt="twitter">  @Munch_Ado</a> &nbsp;&nbsp;&nbsp; <a href="mailto:wecare@munchado.com" style="text-decoration:none; color:#000000"><img src="<?php echo TEMPLATE_IMG_PATH . 'mabiz-mail-icon.jpg'; ?>" style="vertical-align:middle" alt="mail"> wecare@munchado.com</a></p>
                            </td>
                        </tr>
                    </table>

                </td>
            </tr>
        </table><!-- end of table third -->


    </body>
</html>