<?php

namespace Term\Controller;

use MCommons\Controller\AbstractRestfulController;

class TermController extends AbstractRestfulController {

    public function getList() {
        $response = array();
        $response['term']['term_of_use']['title'] = 'Terms of Use';
        $response['term']['term_of_use']['description']['p1'] = 'These are the Terms of Use of Munch Ado, Inc. ("we", "our," or "us") applicable to our web site, www.MunchAdo.com, as well as our products, services, tools and mobile applications that include a link to our Privacy Policy (see below for URL) and/or these Terms of Use (collectively, and each individually, "Site"). For example, for purposes of these Terms of Use, "Site" includes our mobile application that is launched and viewed from certain smartphones, tablets and other devices. The terms "you" and "your" herein refer to the user or viewer of the Site.';
        $response['term']['privacy_link'] = 'The Terms of Use is complemented by our Privacy Policy available at ' . WEB_URL . 'privacy';
        $response['term']['general_use_of_site']['title'] = 'General Use of Site.';
        $response['term']['general_use_of_site']['description']['p1'] = 'The Site is intended for persons who are 18 or older and is for their personal use only. If you are under 18, please do not use the Site. Use of the Site is subject to these Terms of Use as they may be modified from time-to-time at our sole discretion without prior notice. By accessing or using any part of the Site, you agree to abide by (i) all applicable laws; (ii) the current Terms of Use; and (iii) any additional terms that might apply to a specific program accessible via, related to, or associated with the Site (“Program Terms”) which, together, constitute an agreement between you and us. Your continued access or use of the Site following any changes to this agreement constitutes your acceptance of those changes. If you find these terms to be unacceptable, please do not use the Site.';
        $response['term']['general_use_of_site']['description']['p2'] = 'You agree not to affect/interrupt or attempt to affect/interrupt the operation of this Site in any manner. We may at any time and for any reason, in our sole discretion, modify or discontinue the Site or Site Content (as defined in the following section) or terminate or restrict your access to the Site.';
        $response['term']['copyright_intellectual']['title'] = 'Copyright and Intellectual Property.';
        $response['term']['copyright_intellectual']['description']['p1'] = 'The Site and its content (including, without limitation, articles, text, photographs, illustrations, graphics, logos, video material, audio material, software, images, sounds, design, layout, look, appearance, and graphics -- collectively, “Site Content”) are protected by copyright and other intellectual property laws. The Site Content is owned or controlled by us, our suppliers, business partners and/or other third parties. Additionally, this Site itself is protected by copyright as a collective work and/or compilation. You may not reproduce, republish, distribute, sell, store on any other web site or other form of electronic retrieval system, or otherwise use any Site Content without our express permission. If you would like permission to use Site Content, please email us at Copycat@MunchAdo.com.';
        $response['term']['ordering_reservations']['title'] = 'Online Ordering and Reservations.';
        $response['term']['ordering_reservations']['description']['p1'] = 'Through the Site, you may order from (for pick-up and/or delivery (where available)), and make reservations at, various restaurants and other eating establishments featured on the Site (collectively, “Restaurants”). Both “Registered Users” and “Unregistered Users” (as defined below) may place an online order or make a reservation on the Site. The terms herein only apply to orders placed (and reservation made) through this Site; the terms do not apply, for example, if you ordered directly from a Restaurant’s web site. Prices for menu items ordered online will be identified as you place your order, and minimum order amounts may apply. Any applicable delivery fees, taxes, cancellation fees and other amounts due in connection with your order will be identified at the time you place your order. There may be limits on the dollar values, number of orders, delivery areas, number of reservations and size of reserving party which may be placed/made on this Site. For online orders, you are responsible for payment in full of your order by credit card (or other payment option made available on this Site such as Pay Pal) at the time of ordering, and no orders will be processed or fulfilled unless payment in full has been made in advance. Unless otherwise indicated, (i) all of your payments will be paid directly to us; (ii) we will appear as the payee on your credit card (or other billing) statement; and (iii) your credit card number (or similar financial information) will not be provided to any Restaurant.';
        $response['term']['ordering_reservations']['description']['p2'] = 'The inclusion of a Restaurant on our Site, in and of itself, does not constitute an endorsement of such Restaurant (or its menu items) by us.';
        $response['term']['ordering_reservations']['description']['p3'] = 'Consistent with our Privacy Policy, we will provide your name, phone number and, perhaps, other information to Restaurants for which you place an online order or make an online reservation.';
        $response['term']['ordering_reservations']['description']['p4'] = 'You agree not to book more than (1) reservation for your personal use during any one meal. Resale or attempted resale of reservations or ordered food/beverages is prohibited.';
        $response['term']['ordering_reservations']['description']['p5'] = 'Users are asked to contact us via the Site to cancel any reservations that they will be unable to honor at least one (1) hour in advance of scheduled reservation time on the day of the reservation (unless the Restaurant has a different cancellation policy which would then apply). We reserve the right to restrict your access to our services and to your Munch Ado account if you repeatedly (in our sole discretion) fail to show-up for your reservation and fail to timely cancel such reservation. We also reserve the right to restrict your access to our services and to your Munch Ado account if you repeatedly (in our sole discretion) cancel an online order or if you otherwise act in a manner that we deem to be inappropriate, fraudulent, deceptive, unfair and/or in violation of these Terms of Use.';
        $response['term']['ordering_reservations']['description']['p6'] = 'Discounts, coupons and other offers may not be able to be combined with online ordering via the Site. Every Restaurant may not currently offer all menu items listed on this Site and menus are subject to change without prior notice. We (and the Restaurants) may discontinue or change specifications on products/services described and/or displayed on this Site without prior notice. Refunds, if any, of amounts paid for cancelled orders will be identified at the time of cancellation.';
        $response['term']['register_nonregister_user']['title'] = '"Registered Users” and “Non-Registered Users."';
        $response['term']['register_nonregister_user']['description']['p1'] = 'Registered Users” are persons who have a valid registered account with us. Registered Users are required to set up (and maintain) such an account with a user name, password and user profile. Your username and password are for your personal use only. You are responsible for maintaining the confidentiality of this information, and you are responsible for all activities that occur under your account, username and/or password. Only Registered Users can participate in our Loyalty Program (as described below).';
        $response['term']['register_nonregister_user']['description']['p2'] = 'Non-Registered Users” are persons who do not have a valid registered account with us. Non-Registered Users cannot participate in our Loyalty Program, but still may place online orders and make online reservations.';
        $response['term']['loyalty_other_program']['title'] = 'Loyalty Program and Other Programs.';
        $response['term']['loyalty_other_program']['description']['p1'] = 'We may offer certain marketing programs, offers and services to users of the Site (each a “Program” and, collectively, “Programs”) such as a rewards/loyalty program. Any loyalty-related Program or other consumer reward-related program (each a “Loyalty Program”) offered by us on our Site will be subject to these Terms of Use, our Privacy Policy and the Program Terms for such Loyalty Program. Our Loyalty Program is only available to Munch Ado Registered Users. We may offer other Programs as well. We may discontinue, or change the terms and conditions of any Program without prior notice. The terms and condition of each Program may be set forth in these Terms of Use, our Privacy Policy and/or in other written materials associated with a particular Program (including, but not limited to, Program Terms).';
        $response['term']['not_proponent_diet_or_eating_choices']['title'] = 'Not a Proponent of Diet or Eating Choices.';
        $response['term']['not_proponent_diet_or_eating_choices']['description']['p1'] = 'By referring or providing information about a Restaurant, its menu or any particular diet, food-type or eating choice, we are not making any specific claims, warranties or representations regarding the nutritional value, benefits, results, disadvantages or risks of any such Restaurant, menu, diet, food or eating choice. Any information provided by us is for general information purposes only and is not intended as a substitute for professional medical or nutritional advice, treatment or diagnosis.';
        $response['term']['user_content']['title'] = 'User Content.';
        $response['term']['user_content']['descriiption']['p1'] = 'We may post reviews, ratings, comments, and other materials, communications, and content provided by a user (including the identity of such user) on the Site (“User Content”). We are not the publisher or author of User Content, and we may not screen User Content before it is posted. Notwithstanding the foregoing, you acknowledge that we have the right (but not the obligation) to review any User Content that you have submitted to the Site, and to reject, delete, disable, or remove any content that we determine, in our sole discretion, (a) does not comply with the terms and conditions of these Terms of Use; (b) might violate any law, infringe upon the rights of third parties, or subject us to liability for any reason; or (c) might adversely affect our public image, reputation or goodwill. Moreover, we reserve the right to reject, delete, disable, or remove any content at any time, for the reasons set forth above, for any other reason, or for no reason. You agree (and represent and warrant) that any User Content you submit will not be unlawful or infringe on the rights of others. You also agree to be solely responsible for any damages resulting from any User Content you submit. All User Content submitted to us will be treated as non-proprietary and non-confidential. By submitting User Content to us, you automatically grant us the royalty-free, perpetual, worldwide, irrevocable, non-exclusive right to use, publish, reproduce, license, sublicense, distribute, sell, perform, translate, and display such User Content (including any drawings, images, sounds, video recordings, or other data embedded in the User Content and including adaptations and derivative works based on the User Content) for any purpose and in any manner or medium (now existing or hereafter developed).';
        $response['term']['infringement_claims']['title'] = 'Infringement Claims';
        $response['term']['infringement_claims']['description']['p1'] = 'Just as we ask others to respect our intellectual property rights, we respect the intellectual property rights of others. If you believe your work has been used in a manner on the Site that may constitute copyright or trademark infringement, you may notify our agent, who can be reached at:';
        $response['term']['infringement_claims']['description']['p2'] = 'Copyright Agent Munch Ado, Inc. 245 5th Avenue Suite 1002, New York, NY 10016 Email: Mine@MunchAdo.com';
        $response['term']['infringement_claims']['notification']['title'] = 'Please include all of the following in your notification:';
        $response['term']['infringement_claims']['notification']['description'][1] = 'A physical or electronic signature of the person authorized to act on behalf of the owner of an exclusive copyright or trademark that is allegedly infringed;';
        $response['term']['infringement_claims']['notification']['description'][2] = 'A description of the work you claim has been infringed;';
        $response['term']['infringement_claims']['notification']['description'][3] = 'A description of where the material you claim is infringing is located on the Site, including by providing a URL to the page containing the material (if applicable);';
        $response['term']['infringement_claims']['notification']['description'][4] = 'Your address, telephone number, email address, and all other information reasonably sufficient to permit us to contact you;';
        $response['term']['infringement_claims']['notification']['description'][5] = 'A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or trademark owner, its agent, or the law; and';
        $response['term']['infringement_claims']['notification']['description'][6] = 'A statement by you, made under penalty of perjury, that the above information in your notice is accurate, and that you are the copyright or trademark owner, or authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed.';
        $response['term']['disclaimer_warranties']['title'] = 'Disclaimer of Warranties and Limitation of Liability.';
        $response['term']['disclaimer_warranties']['description']['p1'] = 'The Site may contain material that is offensive or otherwise objectionable to you. The Site and all Site Content are provided “AS IS” to the full extent permitted by law. This means that we do not warrant that the Site or Site Content will be (a) fit for any particular purpose; (b) uninterrupted or error-free; or (c) free of defamatory, offensive, or illegal material or defects such as viruses, malfunctions, or harmful components that could damage or allow unauthorized access to your computer or computer network. WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY, QUIET ENJOYMENT, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. NO INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US OR AT OR THROUGH THE SITE SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN. WE MAKE NO REPRESENTATIONS OR WARRANTIES THAT THE SITE (AND RELATED SERVICES, PRODUCTS, OFFERS, ETC.) ARE APPROPRIATE OR AVAILABLE FOR USE IN ALL GEPGRAPHIC LOCATIONS. You acknowledge that the Site and Site Content may contain inaccuracies, typographical mistakes or other errors and we expressly exclude liability for any such inaccuracies typographical mistakes or other errors to the fullest extent permitted by law.Neither we, nor our officers, directors, members, employees, agents, or representatives are liable for any damages resulting from use of the Site or Site Content including, but not limited to, damages caused by defamatory, offensive, or illegal material or damages caused by viruses, malfunctions, or other harmful components accessed through the Site. In no event shall we, and/or our affiliated entities, nor our/their respective officers, directors, members, employees, agents, or representatives, be responsible or liable for any direct, indirect, incidental, special or consequential damages, or damages for loss of profits, revenue, data, or use incurred by you or any third party, whether in an action in contract or tort, arising from or related to content located on (or accessible via) the Site, or related to your access to, or use of, or inability to use the Site, even if we have been advised of the possibility of such damages or losses.';
        $response['term']['disclaimer_warranties']['description']['p2'] = 'It is strictly forbidden for you to create or introduce, or advise others to create or introduce, any type of virus or malware to the Site, which could (or will) cause damage or other harmful effects.';
        $response['term']['disclaimer_warranties']['description']['p3'] = 'The content of the Site is only meant for informative purposes. Therefore, no information, materials, or content contained in the Site shall constitute advice, or substitute for professional advice.';
        $response['term']['disclaimer_warranties']['description']['p4'] = 'Some jurisdictions do not allow the disclaimer or exclusion of certain warranties or the disclaimer or exclusion of certain liabilities. To the extent that they are held to be legally invalid, disclaimers, exclusions, and limitations set forth in these Terms of Use do not apply; however, all other terms and conditions shall apply and remain in full force and effect.';
        $response['term']['links_and_communications']['title'] = 'Links and Communications with Third Party Sites.';
        $response['term']['links_and_communications']['description']['p1'] = 'The Site includes links to other web sites and/or applications that are not maintained by us. We are not responsible for any information, functionality, or content of these web sites and/or applications maintained by third parties (including, but not limited to, those of Restaurants), nor does the presence of the links on our Site mean that we endorse such web sites and/or applications. Your communications with, or use or purchase of products or services from, such third parties directly are subject to the terms of use and privacy policy of such third party.';
        $response['term']['indemnification']['title'] = 'Indemnification.';
        $response['term']['indemnification']['description']['p1'] = 'You agree to defend us, indemnify us, and hold us harmless (as well as our affiliated entities together with our/their respective officers, directors, members, employees, agents, and representatives) from and against all the liabilities, claims, damages, and expenses (including reasonable attorney and professional fees and costs) arising out of your use of the Site; your failure to use the Site; your breach or alleged breach of these Terms of Use, any Program Terms, or our Privacy Policy, or your breach or alleged breach of the copyright, trademark, proprietary or other rights of third parties..';
        $response['term']['acceptance_changes']['title'] = 'Acceptance and Changes.';
        $response['term']['acceptance_changes']['description']['p1'] = 'By using the Site, you agree to accept the current Terms of Use. We may modify these Terms of Use at any time without notice. Your continued use of the Site now, or following any changes in these Terms of Use, will indicate acceptance by you of such rules, changes and/or modifications.';
        $response['term']['applicable_law']['title'] = 'Applicable Law.';
        $response['term']['applicable_law']['description']['p1'] = 'Your use of the Site and any disputes arising out of such use of the Site is subject to the laws of the State of New York without reference to its conflict or choice of law rules, and the parties submit to the exclusive jurisdiction of the state and federal courts located in the State of New York.';
        $response['term']['effective'] = 'Effective: July 30, 2013';


        return $response;
    }

}
