<?php echo $this->content; ?>
<tr>
    <td align="left" style="background-color:#f0ead6;padding-left:30px;padding-right:30px;padding-bottom:45px;">
        <table width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td style="font-size:27px;">Follow us</td>
                <td align="right">
                    <a href="<?php echo $this->facebook_url;?>" target="_blank"><img src="<?php echo TEMPLATE_IMG_PATH.'icon_fb.jpg';?>" border="0" alt="Facebook"></a>
                    <a href="<?php echo $this->instagram_url;?>" target="_blank">
                        <img src="<?php echo TEMPLATE_IMG_PATH .'icon_insta.png';?>" border="0" alt="Instagram">
                    </a>
                </td>
            </tr>
        </table>
    </td>
</tr>
<tr>
    <td align="center" style="padding:35px 0;background:#393838;">
        <a href="http://www.ariawinebar.com/" target="_blank"><img src="<?php echo TEMPLATE_IMG_PATH .'btn_visitariawebsite.jpg';?>" alt="visit aria website" style="display: block;max-width:90%;" border="0"></a>
    </td>
</tr>
</table>
</td>
</tr>
</table>
<!--[if (gte mso 9)|(IE)]>
</td>
</tr>
</table>
<![endif]-->
</body>
</html>